### ISSUE TITLE
Can expose feature for parity-scale-codec with `std/serde`?

### ISSUE THREAD

**Issue by pidb** [paritytech/subxt#1004]
serde is an important serialization framework in the rust ecosystem. It integrates with many ecosystems. I see subxt currently has the parity-scale-codec with `std/serde` feature turned off

```toml
# subxt/Cargo.toml
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }

# subxt/codegen/Cargo.tom
codec = { package = "parity-scale-codec", workspace = true, features = ["derive"] }
```

I think there could be an option for users to optionally enable this feature to provide more flexibility in the generated runtime API
