### ISSUE TITLE
{ code: ServerError(1010), message: "Invalid Transaction", data: Some(RawValue("Transaction has a bad signature")) }

### ISSUE THREAD

**Issue by dayou5168** [paritytech/subxt#1935]
I am trying to write a command line tool for Autonomys. This is my first time to use Subxt. and I got this problem. not sure if it's right place to ask help. but I am gona try.
Here is my code
```rust
#[subxt::subxt(runtime_metadata_path = "./metadata.scale")]
pub mod Autonomys {}


#[tokio::main]
async fn main() -> Result<()> {
    let mnemonic = bip39::Mnemonic::from_str(
        "my-seed-phrase",
    )
    .unwrap();
    let signer = Keypair::from_phrase(&mnemonic, None)?;
    println!("{}", signer.public_key().to_account_id());   
    let moreapi =  OnlineClient::<PolkadotConfig>::from_insecure_url("ws://10.122.1.20:9955/ws").await?;
    let dest_account: AccountId32 = subxt_core::utils::AccountId32::from_str(
        "sucqjmQUPBV6QAWuhorfW1GiXout9kSJ481sKNirTf31cS8jw",
    )
    .unwrap();
    let dest: subxt_core::utils::MultiAddress<AccountId32, ()> =
        subxt_core::utils::MultiAddress::Id(dest_account);

    let balance_transfer_tx = Autonomys::tx()
        .balances()
        .transfer_keep_alive(dest, 3000000000000000000);
    let event = moreapi
        .tx()
        .sign_and_submit_then_watch_default(&balance_transfer_tx, &signer) 
        .await?
        .wait_for_finalized_success()
        .await?;
    Ok(())
}
```
And here is my  Cargo.toml
```toml
[dependencies]
subxt = { version = "0.39", features = ["default", "unstable-light-client"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
sp-core = "35.0.0"
sp-keystore = "0.41.0"
sp-runtime = "40.1.0"
subxt-signer = "0.39.0"
```

when running on IDE. I get `{ code: ServerError(1010), message: "Invalid Transaction", data: Some(RawValue("Transaction has a bad signature")) }`

Gpt/Grok failed to help me . Any help will be appriciated.
