### ISSUE TITLE
Pin PR CI tests against specific substrate; daily compat tests against latest master.

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#334]
Following #329, we could also pin the integration tests carried out in CI to a specific version of substrate, so that breaking changes in substrate don't start breaking out PRs here.

We still want to know about such breaking changes, and for this we can add a new CI file that does scheduled daily runs like:

```
name: Daily compatibility check against substrate master
on:
  schedule:    
    - cron: "0 9 * * *"
```

There would be a lot of code duplication if we copied all of the CI steps over (you can import jobs I think from other files), but it is probably sufficient just to run a daily `cargo test` against latest substrate.

I'm not yet sure how a cron job failure here would be reported to us; I assume as a red tick on master. We'd need to make sure it was fairly obvious and easy to receive notifications for.
