### ISSUE TITLE
Error using polkadot-v0.9.34+ w/ subxt

### ISSUE THREAD

**Issue by drewstone** [paritytech/subxt#741]
There seems to be two different versions of primitive crates at version 7.0.0 in Substrate / Subxt that are not working together. Below is a small example demonstrating this:
```rust
use sp_keyring::AccountKeyring;
use sp_runtime::AccountId32;
use subxt::tx::PairSigner;

fn main() {
    println!("{:?}", get_signer_account_id());
}

pub fn get_signer_account_id() -> AccountId32 {
    let signer = PairSigner::new(AccountKeyring::Alice.pair());
    signer.account_id().clone()
}
```

```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.34" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.34" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.34" }
subxt = { git = "https://github.com/paritytech/subxt.git" }
```

# Errors
```
error[E0277]: the trait bound `sp_keyring::sr25519::sr25519::Pair: subxt::ext::sp_core::Pair` is not satisfied
  --> src/main.rs:10:34
   |
10 |     let signer = PairSigner::new(AccountKeyring::Alice.pair());
   |                  --------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `subxt::ext::sp_core::Pair` is not implemented for `sp_keyring::sr25519::sr25519::Pair`
   |                  |
   |                  required by a bound introduced by this call
   |
   = help: the following other types implement trait `subxt::ext::sp_core::Pair`:
             subxt::ext::sp_core::crypto::Dummy
             subxt::ext::sp_core::ecdsa::Pair
             subxt::ext::sp_core::ed25519::Pair
             subxt::ext::sp_core::sr25519::Pair
             subxt::ext::sp_runtime::sp_application_crypto::ecdsa::AppPair
             subxt::ext::sp_runtime::sp_application_crypto::ed25519::AppPair
             subxt::ext::sp_runtime::sp_application_crypto::sr25519::AppPair
note: required by a bound in `PairSigner::<T, P>::new`
  --> /Users/drew/.cargo/git/checkouts/subxt-d8146022e5587204/8484c18/subxt/src/tx/signer.rs:45:8
   |
45 |     P: Pair,
   |        ^^^^ required by this bound in `PairSigner::<T, P>::new`

error[E0277]: the trait bound `sp_keyring::sr25519::sr25519::Pair: subxt::ext::sp_core::Pair` is not satisfied
  --> src/main.rs:10:18
   |
10 |     let signer = PairSigner::new(AccountKeyring::Alice.pair());
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `subxt::ext::sp_core::Pair` is not implemented for `sp_keyring::sr25519::sr25519::Pair`
   |
   = help: the following other types implement trait `subxt::ext::sp_core::Pair`:
             subxt::ext::sp_core::crypto::Dummy
             subxt::ext::sp_core::ecdsa::Pair
             subxt::ext::sp_core::ed25519::Pair
             subxt::ext::sp_core::sr25519::Pair
             subxt::ext::sp_runtime::sp_application_crypto::ecdsa::AppPair
             subxt::ext::sp_runtime::sp_application_crypto::ed25519::AppPair
             subxt::ext::sp_runtime::sp_application_crypto::sr25519::AppPair
note: required by a bound in `PairSigner`
  --> /Users/drew/.cargo/git/checkouts/subxt-d8146022e5587204/8484c18/subxt/src/tx/signer.rs:34:37
   |
34 | pub struct PairSigner<T: Config, P: Pair> {
   |                                     ^^^^ required by this bound in `PairSigner`

error[E0599]: the method `account_id` exists for struct `PairSigner<_, sp_keyring::sr25519::sr25519::Pair>`, but its trait bounds were not satisfied
  --> src/main.rs:11:12
   |
11 |     signer.account_id().clone()
   |            ^^^^^^^^^^ private field, not a method
   |
  ::: /Users/drew/.cargo/git/checkouts/substrate-7e08433d4c370a21/1cc97dd/primitives/core/src/sr25519.rs:83:1
   |
83 | pub struct Pair(Keypair);
   | --------------- doesn't satisfy `_: subxt::ext::sp_core::Pair`
   |
   = note: the following trait bounds were not satisfied:
           `sp_keyring::sr25519::sr25519::Pair: subxt::ext::sp_core::Pair`
```

CC @1xstj @tbraun96
